Add support for java 1.6 & earlier.
The only difference that I could find between the javac output in 1.7 vs
1.6 is that java 1.6 doesn't include `error: ` or `warning: ` on the
first line, ie:

```
.../Test.java:14: ';' expected
```

instead of:

```
.../Test.java:14: error: ';' expected
```

Tested with java version 1.6.0_65 on Mac OS 10.9.2 specifically, but I
googled errors for Java 5 & Java 4 and they appear to have the same
format.